"use client";
import { useState } from "react";

const nav=["Dashboard","New Case","My Cases","Rights Navigator","Grievance Assistant","Settings"];

export default function Home(){
 const [active,setActive]=useState("Dashboard"); const [story,setStory]=useState(""); const [result,setResult]=useState<any>(null); const [loading,setLoading]=useState(false);
 async function analyze(){setLoading(true);setResult(null);try{const r=await fetch("/api/agents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({story})});setResult(await r.json());}finally{setLoading(false)}}
 return <div className="app"><aside className="side"><div className="brand"><b>NX</b><div><strong>NIVARAN X</strong><small>Investor Rights Intelligence</small></div></div>{nav.map((n)=><button key={n} className={active===n?"nav active":"nav"} onClick={()=>setActive(n)}>{n}</button>)}<div className="trust">● System protected<br/><span>Privacy-first • Guardrails active</span></div></aside><main><header><div><small>TRACK B</small><h1>{active}</h1></div><span className="online">● AI system ready</span></header><section className="wrap">
 {active==="Dashboard"&&<><div className="hero"><div><span>INVESTOR RESILIENCE</span><h2>Turn a confusing investor problem into a verified action path.</h2><p>NIVARAN X reconstructs the case, checks evidence, identifies the relevant official grievance pathway and explains what information is still missing.</p><button className="primary" onClick={()=>setActive("New Case")}>Start a New Case →</button></div><div className="heroStats"><b>6</b><span>AI agents</span><b>5</b><span>Safety checks</span><b>1</b><span>Unified case view</span></div></div><div className="cards"><Card n="01" t="Case Reconstruction" d="Convert an investor story into a structured timeline."/><Card n="02" t="Evidence Intelligence" d="Map evidence to claims and identify missing proof."/><Card n="03" t="Rights Navigator" d="Find the relevant official grievance route without inventing rules."/></div></>}
 {active==="New Case"&&<div className="panel"><span>NEW INVESTOR CASE</span><h2>Describe what happened</h2><p>Use plain language. Do not enter passwords, OTPs, PINs or unnecessary sensitive information.</p><textarea value={story} onChange={e=>setStory(e.target.value)} placeholder="Example: My broker deducted ₹2,500 from my account. I contacted customer care but they have not explained the deduction."/><button className="primary" disabled={!story.trim()||loading} onClick={analyze}>{loading?"Running AI agents…":"Run NIVARAN AI Analysis →"}</button>{result?.case&&<CaseView data={result.case}/>}</div>}
 {active==="My Cases"&&<div className="panel"><span>CASE MANAGEMENT</span><h2>Your cases</h2><p>Cases created in this demo session will appear here after analysis.</p>{result?.case?<CaseView data={result.case}/>:<div className="empty">No analyzed cases yet. Start a new case.</div>}</div>}
 {active==="Rights Navigator"&&<Info title="Rights Navigator" text="This module is designed to surface source-grounded grievance pathways. Regulatory applicability must always be verified against current official sources."/>}
 {active==="Grievance Assistant"&&<Info title="Grievance Assistant" text="After case analysis, NIVARAN can organize the facts, evidence and requested resolution into a reviewable grievance draft. It does not guarantee an outcome or provide individualized investment advice."/>}
 {active==="Settings"&&<Info title="Settings" text="Language, privacy and accessibility controls will be connected here. Privacy-by-design remains a core NIVARAN X guardrail."/>}
 </section></main></div>
}
function Card({n,t,d}:{n:string;t:string;d:string}){return <div className="card"><span>{n}</span><h3>{t}</h3><p>{d}</p></div>}
function Info({title,text}:{title:string;text:string}){return <div className="panel"><span>NIVARAN X</span><h2>{title}</h2><p>{text}</p></div>}
function CaseView({data}:any){return <div className="case"><div className="caseTop"><div><span>CASE ID</span><h3>{data.caseId}</h3></div><div className="score"><b>{data.readiness}%</b><small>information readiness</small></div></div><div className="caseGrid"><div><h3>Case Reconstruction</h3><p>{data.issue}</p><p><b>Category:</b> {data.category}</p><p><b>Entity:</b> {data.entity||"Not identified"}</p></div><div><h3>Missing Information</h3>{data.missing.length?data.missing.map((x:string)=><div className="missing" key={x}>⚠ {x}</div>):<div className="ok">✓ No critical gaps detected</div>}</div></div><div><h3>Agent Trace</h3>{data.agentTrace.map((x:any)=><div className="agent" key={x.agent}><b>{x.agent}</b><span>{x.note}</span><em>{x.status}</em></div>)}</div><div className="next"><b>Next action</b><br/>{data.nextAction}</div><a href={data.sources?.[0]?.url} target="_blank">Open official grievance source ↗</a></div>}
